name: Fluid Mesh Data Processing and Commit

on:
  push:
    branches:
      - "**"  # Triggers on any branch
  workflow_dispatch:

jobs:
  process_fluid_mesh_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Debug Repository Structure
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Verify Mesh Script Exists
        run: |
          echo "🔎 Checking if generate_blender_mesh_format.py exists..."
          ls -R "$GITHUB_WORKSPACE/src"
          if [ ! -f "$GITHUB_WORKSPACE/src/generate_blender_mesh_format.py" ]; then
            echo "❌ Error: generate_blender_mesh_format.py not found in src directory!"
            exit 1
          else
            echo "✅ Script found: generate_blender_mesh_format.py"
          fi

      - name: Run Fluid Mesh Data Processing Script
        run: |
          python "$GITHUB_WORKSPACE/src/generate_blender_mesh_format.py"

      - name: Debug Output Directory
        run: ls -R "$GITHUB_WORKSPACE/data/testing-input-output"

      # --- COMMENTED OUT: Test Steps ---
      # - name: Run Unit Tests (Mesh Processing)
      #   run: pytest tests/test_mesh_processing_pipeline.py --verbose

      # --- REMOVED: Upload Generated Fluid Mesh JSON Artifact ---
      # This step is no longer needed as the file is committed directly.

      - name: Commit and Push Fluid Mesh Data to Repository
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

          cd "$GITHUB_WORKSPACE"

          GENERATED_FILE="data/testing-input-output/fluid_mesh_data.json"
          
          if [ -f "$GENERATED_FILE" ]; then
            git add "$GENERATED_FILE"
            git status

            if [[ $(git diff --cached --quiet; echo $?) -ne 0 ]]; then
              git commit -m "Auto-update: Generated animated fluid mesh data (JSON)"
              git push origin HEAD
            else
              echo "✅ No changes to commit!"
            fi
          else
            echo "❌ No fluid mesh data JSON detected, skipping commit."
          fi
