name: Fluid Mesh Processing and Commit

on:
  push:
    branches:
      - "**"  # Triggers on any branch
  workflow_dispatch:

jobs:
  process_fluid_mesh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Keeping Python 3.9 for compatibility

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "⚠️ Warning: Some dependencies might not be available."

      - name: Install system dependencies (Keep TBB if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y libtbb-dev

      - name: Debug Repository Structure
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Verify Script Exists
        run: |
          echo "🔎 Checking if generate_blender_mesh_format.py exists..."
          ls -R "$GITHUB_WORKSPACE/src"

          if [ ! -f "$GITHUB_WORKSPACE/src/generate_blender_mesh_format.py" ]; then
            echo "❌ Error: generate_blender_mesh_format.py not found in src directory!"
            exit 1
          else
            echo "✅ Script found: generate_blender_mesh_format.py"
          fi

      - name: Run Fluid Mesh Processing Script
        env:
          OUTPUT_FORMAT: abc  # Output format for Alembic mesh
        run: |
          cd "$GITHUB_WORKSPACE/src"
          python generate_blender_mesh_format.py

      - name: Debug Output Directory
        run: ls -R "$GITHUB_WORKSPACE/data/testing-input-output"

      # ✅ Execute Unit & Integration Tests After Output File Generation
      # - name: Run Unit Tests
      #   run: pytest tests/test_mesh_processing_pipeline.py --verbose

      - name: Commit and Push Alembic Fluid Mesh to Repository
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

          cd "$GITHUB_WORKSPACE"

          if [ -f "data/testing-input-output/fluid_mesh.abc" ]; then
            git add "data/testing-input-output/fluid_mesh.abc"
            git status

            if [[ $(git diff --cached --quiet; echo $?) -ne 0 ]]; then
              git commit -m "Auto-update: Generated Alembic fluid mesh"
              git push origin HEAD
            else
              echo "✅ No changes to commit!"
            fi
          else
            echo "❌ No Alembic fluid mesh detected, skipping commit."
          fi
